#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_MTU (1500)

#ifndef FREERTOS
#define HAVE_USRSCTP
#endif

#define VIDEO_RB_SIZE_LENGTH 256
#define AUDIO_RB_SIZE_LENGTH 256
#define VIDEO_RB_DATA_LENGTH (CONFIG_MTU * 64)
#define AUDIO_RB_DATA_LENGTH (CONFIG_MTU * 64)

#endif // CONFIG_H_
