#ifndef CONFIG_H_
#define CONFIG_H_

// uncomment this if you want to handshake with a aiortc
// #define CONFIG_LIBPEER_DTLS_USE_ECDSA 1

#ifndef CONFIG_LIBPEER_SCTP_MTU
#define CONFIG_LIBPEER_SCTP_MTU (1200)
#endif
#ifndef CONFIG_LIBPEER_MTU
#define CONFIG_LIBPEER_MTU (1300)
#endif

#ifndef CONFIG_LIBPEER_USE_LWIP
#define CONFIG_LIBPEER_USE_LWIP 0
#endif

#ifndef CONFIG_LIBPEER_MBEDTLS_DEBUG
#define CONFIG_LIBPEER_MBEDTLS_DEBUG 0
#endif

#ifndef CONFIG_LIBPEER_MBEDTLS_2_X
#define CONFIG_LIBPEER_MBEDTLS_2_X 0
#endif

#if CONFIG_LIBPEER_MBEDTLS_2_X
#define RSA_KEY_LENGTH 512
#else
#define RSA_KEY_LENGTH 1024
#endif

#ifndef CONFIG_LIBPEER_DTLS_USE_ECDSA
#define CONFIG_LIBPEER_DTLS_USE_ECDSA 0
#endif

#ifndef CONFIG_LIBPEER_USE_USRSCTP
#define CONFIG_LIBPEER_USE_USRSCTP 1
#endif

#ifndef CONFIG_LIBPEER_VIDEO_BUFFER_SIZE_MTUS
#define CONFIG_LIBPEER_VIDEO_BUFFER_SIZE_MTUS 256
#endif
#ifndef CONFIG_LIBPEER_AUDIO_BUFFER_SIZE_MTUS
#define CONFIG_LIBPEER_AUDIO_BUFFER_SIZE_MTUS 256
#endif
#ifndef CONFIG_LIBPEER_DATA_BUFFER_SIZE_MTUS
#define CONFIG_LIBPEER_DATA_BUFFER_SIZE_MTUS 128
#endif

#ifndef CONFIG_LIBPEER_VIDEO_BUFFER_SIZE
#define CONFIG_LIBPEER_VIDEO_BUFFER_SIZE (CONFIG_LIBPEER_MTU * CONFIG_LIBPEER_VIDEO_BUFFER_SIZE_MTUS)
#endif

#ifndef CONFIG_LIBPEER_AUDIO_BUFFER_SIZE
#define CONFIG_LIBPEER_AUDIO_BUFFER_SIZE (CONFIG_LIBPEER_MTU * CONFIG_LIBPEER_AUDIO_BUFFER_SIZE_MTUS)
#endif

#ifndef CONFIG_LIBPEER_DATA_BUFFER_SIZE
#define CONFIG_LIBPEER_DATA_BUFFER_SIZE (CONFIG_LIBPEER_SCTP_MTU * CONFIG_LIBPEER_DATA_BUFFER_SIZE_MTUS)
#endif

#ifndef CONFIG_LIBPEER_SDP_BUFFER_SIZE
#define CONFIG_LIBPEER_SDP_BUFFER_SIZE 8096
#endif

#ifndef CONFIG_LIBPEER_MQTT_BUFFER_SIZE
#define CONFIG_LIBPEER_MQTT_BUFFER_SIZE 4096
#endif

#ifndef CONFIG_LIBPEER_HTTP_BUFFER_SIZE
#define CONFIG_LIBPEER_HTTP_BUFFER_SIZE 4096
#endif

#ifndef CONFIG_LIBPEER_TLS_READ_TIMEOUT
#define CONFIG_LIBPEER_TLS_READ_TIMEOUT 3000
#endif

#ifndef CONFIG_LIBPEER_KEEPALIVE_TIMEOUT
#define CONFIG_LIBPEER_KEEPALIVE_TIMEOUT 10000
#endif

#ifndef CONFIG_LIBPEER_AUDIO_DURATION
#define CONFIG_LIBPEER_AUDIO_DURATION 20
#endif

#ifndef CONFIG_LIBPEER_IPV6
#define CONFIG_LIBPEER_IPV6 0
#endif

#ifndef CONFIG_LIBPEER_IFACE_PREFIX
// empty will use first active interface
#define CONFIG_LIBPEER_IFACE_PREFIX ""
#endif

#ifndef CONFIG_LIBPEER_LOG_REDIRECT
#define CONFIG_LIBPEER_LOG_REDIRECT 0
#endif

#ifdef CONFIG_LIBPEER_LOG_LEVEL_ERROR
#define LOG_LEVEL LEVEL_ERROR
#endif  // CONFIG_LIBPEER_LOG_LEVEL_ERROR
#ifdef CONFIG_LIBPEER_LOG_LEVEL_WARN
#define LOG_LEVEL LEVEL_WARN
#endif  // CONFIG_LIBPEER_LOG_LEVEL_WARN
#ifdef CONFIG_LIBPEER_LOG_LEVEL_INFO
#define LOG_LEVEL LEVEL_INFO
#endif  // CONFIG_LIBPEER_LOG_LEVEL_INFO
#ifdef CONFIG_LIBPEER_LOG_LEVEL_DEBUG
#define LOG_LEVEL LEVEL_DEBUG
#endif  // CONFIG_LIBPEER_LOG_LEVEL_DEBUG

// Disable MQTT and HTTP signaling
#ifndef CONFIG_LIBPEER_DISABLE_PEER_SIGNALING
#define CONFIG_LIBPEER_DISABLE_PEER_SIGNALING 0
#endif

#endif  // CONFIG_H_
